### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by manikantag** [tiaanduplessis/wenk#11]
Hi,

Can you please mention the supported browsers & especially IE versions? Better to add those details in README for 'greater good' 

Thanks.

**Comment by tiaanduplessis** [comment]
Good idea 👍. Added to README

**Comment by manikantag** [comment]
Oh, thanks.

> _browsers are currently missing support:
> IE (8,10)_

Hmmm, for sometime we need to support IE10. As per the doiuse.com report, only below 2 properties are causing this: `rem (root em) units 3, CSS pointer-events (for HTML)`, and I think, for me, these 2 are easy to fix or okay to live without.

Thanks.
