### ISSUE TITLE
Inline HTML

### ISSUE THREAD

**Issue by alexanderlloyd** [tiaanduplessis/wenk#13]
Hi! Great work! Would it possible to add a feature to allow for inline HTML? Thanks!

**Comment by tiaanduplessis** [comment]
Hi @alexanderlloyd!  I'm not quite sure what you mean by inline HTML? Could you give a usage example?

**Comment by alexanderlloyd** [comment]
Hi @tiaanduplessis,

I mean allowing html tags, `data-wenk="<strong>hello</strong>`" for example.

Thanks!

**Comment by tiaanduplessis** [comment]
@alexanderlloyd unfortunately I don't believe this will be possible due to the way `attr()` CSS function handles string types. You should be able to get this kind of functionality from JS based tooltip library such as [tippyjs](https://github.com/atomiks/tippyjs)
