### ISSUE TITLE
Create a message loop

### ISSUE THREAD

**Issue by diegotfcastro** [tiaanduplessis/wenk#15]
Hello everyone, first of all congratulations for the work. Really enjoyed.
Actually, it's not an issue, it's a question, I'm trying to create a messaging loop but without success so far. Can you help me ?

**Comment by jackmcpickle** [comment]
@diegotfcastro can you explain what you mean by  messaging loop? A screenshot or example. Not sure how wenk can be used to help.

**Comment by diegotfcastro** [comment]
Please Delete my post, wrong place. Sorry.
