### ISSUE TITLE
Scss files

### ISSUE THREAD

**Issue by jackmcpickle** [tiaanduplessis/wenk#6]
Are you open to add scss src files to? Or do you feel it's better in a separate repo?

**Comment by tiaanduplessis** [comment]
@jackmcpickle sure I'm open to it! 👍. Since it is a relatively small project I'm sure adding scss src will be fine.

**Comment by jackmcpickle** [comment]
Solved in https://github.com/mightyCrow/wenk/pull/9

**Comment by tiaanduplessis** [comment]
#9  Has been merged in
